# Generated by Django 3.0 on 2023-06-27 10:05

from django.apps import apps as global_apps
from django.db import migrations


def add_data_in_table(apps, schema_editor):

    try:
        ProfileOld = apps.get_model("oc_lettings_site", "Profile")
    except:
        return

    ProfileNew = apps.get_model("profiles", "Profile")
    for profile_old in ProfileOld.objects.all():
        profile_new = ProfileNew(
            user=profile_old.user,
            favorite_city=profile_old.favorite_city,
        )
        profile_new.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(add_data_in_table),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS oc_lettings_site_profile;",
        ),
    ]
    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))
