# Generated by Django 3.0 on 2023-06-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
    ]
